language: python

python:
  - "2.6"
  - "2.7"

addons:
  apt:
    packages:
    - python-dev

install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install importlib; fi
  - "pip install junos-eznc"
  - "pip install jxmlease"
  - "pip install nose"
  - "pip install mock"
  - "pip install unittest2"

script: python tests/runtests.py -n unit.modules.junos_test
