language: python

python:
  - "2.6"
  - "2.7"

addons:
  apt:
    packages:
    - python-dev

install:
  - "pip install junos-eznc"
  - "pip install jxmlease"
  - "pip install -r requirements/dev_python26.txt"
  - "pip install -r requirements/zeromq.txt"
  - "pip install nose"

script: python ./tests/runtests.py -n unit.modules.junos
