language: python

python:
  - '2.6'
  - '2.7'

before_install:

  #- sudo apt-get install -y -o DPkg::Options::=--force-confold python-software-properties || sudo apt-get install -y -o DPkg::Options::=--force-confold software-properties-common
  #- sudo add-apt-repository -y ppa:saltstack/salt || sudo add-apt-repository ppa:saltstack/salt
  - sudo apt-get update
  #- sudo apt-get install -y -o DPkg::Options::=--force-confold python-crypto python-jinja2 python-m2crypto python-yaml python-zmq msgpack-python
  - sudo apt-get install -y -o DPkg::Options::=--force-confold git swig supervisor rabbitmq-server ruby
  - (git describe && git fetch --tags) || (git remote add upstream git://github.com/saltstack/salt.git && git fetch --tags upstream)
  - pip install http://dl.dropbox.com/u/174789/m2crypto-0.20.1.tar.gz
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ordereddict; fi"

install: pip install -r requirements.txt --use-mirrors
script: sudo -E /home/travis/virtualenv/python2.6/bin/python setup.py test --runtests-opts='--run-destructive --sysinfo -v'

notifications:
  irc:
    channels: "irc.freenode.org#salt-devel"
    on_success: change
    on_failure: change
